# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-07-14 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stockid', models.IntegerField()),
                ('balance_type', models.CharField(choices=[('買進', '買進'), ('賣出', '賣出')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('share', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Category')),
            ],
        ),
    ]
